// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addChirpyRedByUserID = `-- name: AddChirpyRedByUserID :one
UPDATE users
SET is_chirpy_red = true, updated_at = NOW()
WHERE id = $1
RETURNING id, email, updated_at, is_chirpy_red
`

type AddChirpyRedByUserIDRow struct {
	ID          uuid.UUID
	Email       string
	UpdatedAt   time.Time
	IsChirpyRed bool
}

func (q *Queries) AddChirpyRedByUserID(ctx context.Context, id uuid.UUID) (AddChirpyRedByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, addChirpyRedByUserID, id)
	var i AddChirpyRedByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UpdatedAt,
		&i.IsChirpyRed,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, hashed_password, is_chirpy_red)
VALUES (
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1,
  $2,
  false
)
RETURNING id, email, created_at, is_chirpy_red
`

type CreateUserParams struct {
	Email          string
	HashedPassword string
}

type CreateUserRow struct {
	ID          uuid.UUID
	Email       string
	CreatedAt   time.Time
	IsChirpyRed bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.HashedPassword)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.IsChirpyRed,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, email, hashed_password, is_chirpy_red FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const updateCredsByUserID = `-- name: UpdateCredsByUserID :one
UPDATE users
SET email = $2, hashed_password = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, email, updated_at, is_chirpy_red
`

type UpdateCredsByUserIDParams struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
}

type UpdateCredsByUserIDRow struct {
	ID          uuid.UUID
	Email       string
	UpdatedAt   time.Time
	IsChirpyRed bool
}

func (q *Queries) UpdateCredsByUserID(ctx context.Context, arg UpdateCredsByUserIDParams) (UpdateCredsByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, updateCredsByUserID, arg.ID, arg.Email, arg.HashedPassword)
	var i UpdateCredsByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UpdatedAt,
		&i.IsChirpyRed,
	)
	return i, err
}
