// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, hashed_password)
VALUES (
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1,
  $2
)
RETURNING id, created_at, updated_at, email
`

type CreateUserParams struct {
	Email          string
	HashedPassword string
}

type CreateUserRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.HashedPassword)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, email, hashed_password FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}

const updateCredsByUserID = `-- name: UpdateCredsByUserID :one
UPDATE users
SET email = $2, hashed_password = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, email, updated_at
`

type UpdateCredsByUserIDParams struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
}

type UpdateCredsByUserIDRow struct {
	ID        uuid.UUID
	Email     string
	UpdatedAt time.Time
}

func (q *Queries) UpdateCredsByUserID(ctx context.Context, arg UpdateCredsByUserIDParams) (UpdateCredsByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, updateCredsByUserID, arg.ID, arg.Email, arg.HashedPassword)
	var i UpdateCredsByUserIDRow
	err := row.Scan(&i.ID, &i.Email, &i.UpdatedAt)
	return i, err
}
